In [24]:
import pandas as pd 
import numpy as np

### Q1: Installed pandas version

In [25]:

pd.__version__

'2.0.1'

In [26]:
car_price_data='data_files/housing_data.csv'

In [27]:
df = pd.read_csv(car_price_data)

In [28]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms   
0    -122.23     37.88                41.0        880.0           129.0  \
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [29]:
df.describe()

longitude      latitude  housing_median_age   total_rooms   
count  20640.000000  20640.000000        20640.000000  20640.000000  \
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income   
count    20433.000000  20640.000000  20640.000000   20640.000000  \
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

### Q2: 
#### How many columns are in the dataset?

In [20]:
"""
df.shape returns tuple (row_count, column_count)
To get column count, return the second item from the tuple
"""

df.shape
df.shape[1]


10

### Question 3
#### Which columns in the dataset have missing values?

In [32]:
df.isnull().sum() > 0
# total_bedrooms has the missing

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms         True
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

### Question 4
#### How many unique values does the ocean_proximity column have?

In [43]:
# 
df.ocean_proximity.unique()

len(df.ocean_proximity.unique())

5

### Question 5
#### What's the average value of the median_house_value for the houses located near the bay?


In [51]:
df[df["ocean_proximity"]=='NEAR BAY'].median_house_value.mean()
## 259212

259212.31179039303

### Question 6
#### Calculate the average of total_bedrooms column in the dataset.
#### Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
#### Now, calculate the average of total_bedrooms again.
#### Has it changed?

In [52]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms   
0    -122.23     37.88                41.0        880.0           129.0  \
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [69]:
# 6.1. Average of total_bedrooms column
total_bedrooms_avg = df.total_bedrooms.mean()
# 537

# 6.2. Use the fillna method to fill the missing values in total_bedrooms with the mean value
df.total_bedrooms.fillna(total_bedrooms_avg, inplace=True)

# 6.3. Calculate the average of total_bedrooms again
updated_total_bedrooms_avg = df.total_bedrooms.mean()
updated_total_bedrooms_avg
# 537 
# The average is same because the null values are filled by average values


537.8705525375617

In [68]:
df.isnull().sum()>0

longitude             False
latitude              False
housing_median_age    False
total_rooms           False
total_bedrooms        False
population            False
households            False
median_income         False
median_house_value    False
ocean_proximity       False
dtype: bool

### Question 7
#### Select all the options located on islands.
#### Select only columns housing_median_age, total_rooms, total_bedrooms.
#### Get the underlying NumPy array. Let's call it X.
#### Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
#### Compute the inverse of XTX.
#### Create an array y with values [950, 1300, 800, 1000, 1300].
#### Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
#### What's the value of the last element of w?

In [79]:
"""
Select all the options located on islands.
Select only columns housing_median_age, total_rooms, total_bedrooms
"""

df_island = df[df['ocean_proximity']=='ISLAND']
df_island.head()
df_island = df_island[["housing_median_age", "total_rooms", "total_bedrooms"]]

In [90]:
# Get the underlying NumPy array. Let's call it X.
X = df_island.to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [98]:
"""
Compute matrix-matrix multiplication between the transpose of X and X. 
To get the transpose, use X.T. Let's call the result XTX.
"""

XT = X.T
XTX = XT.dot(X)
XTX


array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [ ]:
# Compute the inverse of XTX.

IXTX = np.linalg.inv(XTX)
IXTX


In [111]:
# Create an array y with values [950, 1300, 800, 1000, 1300].

y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [112]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# What's the value of the last element of w?

z = IXTX.dot(XT)

w = z.dot(y)
w
w[-1]


5.699229455065578